declare namespace _default {
    namespace data {
        const bg: string;
        const wifi: string;
        const apps: string;
        const lock: string;
        const location: string;
        const weather: string;
        const scroll_inactive: string;
        const time_bg: string;
        const music_bg: string;
        const storage_bg: string;
        const tap_to_speak_bg: string;
        const refrigerator_doors_bg: string;
        const recepie_bg: string;
        const bottom_tab_bg: string;
        const shuffle: string;
        const back: string;
        const play: string;
        const next: string;
        const range: string;
        const vegetables_range_white: string;
        const green_range: string;
        const orange_range: string;
        const violet_range: string;
        const microphone: string;
        const clock: string;
        const favourite_active: string;
        const favourite_inactive: string;
        const home_icon: string;
        const storage_icon: string;
        const music_icon: string;
        const settings_icon: string;
        const view_icon: string;
        const add_icon: string;
        const pink_button: string;
        const storage_settings: string;
        const dinner_text: string;
        const all_recp_text: string;
        const food_remain: string;
        const home_txt: string;
        const storage_txt: string;
        const music_txt: string;
        const settings_txt: string;
        const audio_assist1: string;
        const audio_assist2: string;
        const your_storage: string;
        const view_text: string;
        const add_text: string;
        const door_text: string;
        const time: string;
        const day_date: string;
        const username: string;
        const location_city: string;
        const temp_red: string;
        const music_cover_image: string;
        const song_name: string;
        const song_genre: string;
        const vegetable_percentage: string;
        const fruits_percentage: string;
        const meat_percentage: string;
        const st_items: {
            img_path: string;
            food_name: string;
            item_weight: string;
        }[];
        const door_status: string;
        const door_status_toggle: string;
        const superfreeze_toggle_txt: string;
        const superfreeze_toggle_txt_bool: string;
        const bottom_box_left_toggle_text: string;
        const bottom_box_right_toggle_text: string;
        const crisp_fresh_toggle_txt: string;
        const crisp_fresh_toggle_txt_bool: string;
        const recp_1_image: string;
        const recp_1_name: string;
        const recp_1_time: string;
        const recp_1_type: string;
        const recp_1_user_reaction: string;
        const recp_2_image: string;
        const recp_2_name: string;
        const recp_2_time: string;
        const recp_2_type: string;
        const recp_2_user_reaction: string;
        const recp_3_image: string;
        const recp_3_name: string;
        const recp_3_time: string;
        const recp_3_type: string;
        const recp_3_user_reaction: string;
    }
    function onInit(): void;
    function onInit(): void;
    function getRecipeList(e: any): void;
    function getRecipeList(e: any): void;
    function date_time_calc(e: any): void;
    function date_time_calc(e: any): void;
    function superfreeze_onSwitchChange(e: any): void;
    function superfreeze_onSwitchChange(e: any): void;
    function crispfresh_onSwitchChange(e: any): void;
    function crispfresh_onSwitchChange(e: any): void;
    function door_lock_onclick(e: any): void;
    function door_lock_onclick(e: any): void;
}
export default _default;
